In [4]:
import json,os
from glob import glob


def writejson(path,arr,name):
    try:
        os.mkdir(path+'preds/')
    except:
        pass
    f = open(path+'preds/'+name,'w')
    json.dump(arr.tolist(),f)
    f.close()

## The test set of this has to be fixed

In [5]:
path = 'data/datasets/uci_adult/'
synthfols = glob("data/datasets/uci_adult/synthetic/*_version0/")
paths = [path]
paths.extend(synthfols)

In [6]:
def task(path):  
    if os.path.exists(path+'preds/noisylabels_peerloss_pred') == False:
        os.system('python3 fair-classification-with-noisy-labels/run.py --path '+path)
    return path,"Done"

In [ ]:
from multiprocessing.pool import ThreadPool as Pool

pool = Pool(10)
for result in pool.imap_unordered(task, paths):
    print(result)

[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.7807947  0.02164578]
 [0.2192053  0.97835422]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79915829 0.06182872]
 [0.20084171 0.93817128]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.21920529801324506, 0.021645780387345548], [0.2008417114800094, 0.0618287208046826]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.78189749 0.02128892]
 [0.21810251 0.97871108]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79796098 0.06185567]
 [0.20203902 0.93814433]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.21810250817884402, 0.021288921071687228], [0.2020390157827664, 0.061855670103092786]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.8122449 0.0171327]
 [0.1877551 0.9828673]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79499596 0.07281376]
 [0.20500404 0.92718624]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.18775510204081636, 0.017132697591724533], [0.20500403551251012, 0.0728137577753385]].
[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.80412931 0.01898964]
 [0.19587069 0.98101036]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.78436764 0.06798705]
 [0.21563236 0.93201295]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.1958706873132301, 0.01898963542799159], [0.2156323644933229, 0.06798705008569794]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.91604513 0.04908616]
 [0.08395487 0.95091384]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80030381 0.06224467]
 [0.19969619 0.93775533]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.08395486708739719, 0.04908616187989556], [0.19969619069876143, 0.06224466636404902]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.83929931 0.03265744]
 [0.16070069 0.96734256]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79547063 0.06510814]
 [0.20452937 0.93489186]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.16070068545316074, 0.03265743809709498], [0.2045293701344657, 0.06510813710542662]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.37, Test Accuracy: 85.78, Training Violation: 7.33, Test Violation: 13.22, Time cost: 10.071791410446167
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.1_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 83.27, Test Accuracy: 83.32, Training Violation: 7.25, Test Violation: 5.96, Time cost: 8.61246395111084
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.3_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 83.11, Test Accuracy: 82.68, Training Violation: 8.89, Test Violation: 9.07, Time cost: 10.721767902374268
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.4_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 84.33, Test Accuracy: 83.81, Training Violation: 3.38, Test Violation: 2.82, Time cost: 13.90065336227417
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 89.85, Test Accuracy: 89.35, Training Violation: 5.41, Test Violation: 6.05, Time cost: 18.636563777923584
[INFO][RUN] Surrogate Loss.
[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.93036425 0.06105064]
 [0.06963575 0.93894936]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80472385 0.06180532]
 [0.19527615 0.93819468]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.0696357514539333, 0.06105063890203499], [0.19527615412143629, 0.0618053216571236]].
('data/datasets/uci_adult/synthetic/female_baserate0.2_version0/', 'Done')


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 87.37, Test Accuracy: 86.62, Training Violation: 7.64, Test Violation: 4.33, Time cost: 10.718986988067627
[INFO][RUN] Surrogate Loss.
[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.94110032 0.08187135]
 [0.05889968 0.91812865]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79853693 0.06220531]
 [0.20146307 0.93779469]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.0588996763754045, 0.08187134502923976], [0.20146307477937764, 0.06220530591376472]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.95632133 0.08481787]
 [0.04367867 0.91518213]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79839086 0.06480903]
 [0.20160914 0.93519097]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.04367866549604915, 0.08481786758840737], [0.20160914179104472, 0.06480903467453603]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.9711835  0.10074774]
 [0.0288165  0.89925226]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80073801 0.06234628]
 [0.19926199 0.93765372]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.02881649961449495, 0.10074773711137353], [0.19926199261992616, 0.06234627924269287]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 82.64, Test Accuracy: 82.2, Training Violation: 9.39, Test Violation: 10.94, Time cost: 11.306433200836182
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.5_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 82.45, Test Accuracy: 82.8, Training Violation: 9.58, Test Violation: 10.04, Time cost: 9.726747989654541
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.6_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 82.58, Test Accuracy: 82.11, Training Violation: 11.23, Test Violation: 12.08, Time cost: 8.392390966415405
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.7_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 82.48, Test Accuracy: 82.85, Training Violation: 12.38, Test Violation: 11.98, Time cost: 3.1173348426818848
[INFO][RUN] Surrogate Loss.
[[1. 0.]
 [0. 1.]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.98075271 0.14554374]
 [0.01924729 0.85445626]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80057703 0.06326589]
 [0.19942297 0.93673411]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.019247293349372696, 0.14554374488961574], [0.19942296595499132, 0.06326588771729835]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


['data/datasets/uci', 'adult/synthetic/gender', 'flip', 'labels0.1', 'version0/']
[[0.98502674 0.03936478]
 [0.01497326 0.96063522]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.48769406 0.11089551]
 [0.51230594 0.88910449]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.8026592  0.06079772]
 [0.1973408  0.93920228]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.5123059447179099, 0.11089550790724745], [0.19734079776067182, 0.06079772079772083]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


['data/datasets/uci', 'adult/synthetic/gender', 'flip', 'labels0.2', 'version0/']
[[0.96748663 0.07896508]
 [0.03251337 0.92103492]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.44473607 0.2044275 ]
 [0.55526393 0.7955725 ]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80091292 0.06201155]
 [0.19908708 0.93798845]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.5552639253426654, 0.204427497087173], [0.1990870786516854, 0.06201155283724091]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 83.05, Test Accuracy: 83.22, Training Violation: 14.43, Test Violation: 14.43, Time cost: 7.630059719085693
[INFO][RUN] Surrogate Loss.


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 377, in <module>
    sl_result = run_surrogate(tolerance, est=True)
  File "fair-classification-with-noisy-labels/run.py", line 345, in run_surrogate
    sweep.fit(X_train, Y_noised, sensitive_features=A_train)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py", line 87, in fit
    X, y, enforce_binary_labels=is_classification_reduction, **kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/fairlearn/_input_validation.py", line 75, in _validate_and_reformat_input
    sensitive_features = check_array(sensitive_features, ensure_2d=False, dtype=None)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/home/avijit/anaconda3/envs/noisy/lib/python3.7/site-packages/sklearn/utils/validat

('data/datasets/uci_adult/synthetic/female_baserate0.9_version0/', 'Done')
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.34, Test Accuracy: 85.31, Training Violation: 7.13, Test Violation: 5.83, Time cost: 3.9146578311920166
[INFO][RUN] Surrogate Loss.
['data/datasets/uci', 'adult/synthetic/gender', 'flip', 'labels0.3', 'version0/']
[[0.95582888 0.11681583]
 [0.04417112 0.88318417]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.43126308 0.3016185 ]
 [0.56873692 0.6983815 ]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80221316 0.06038317]
 [0.19778684 0.93961683]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.5687369155617585, 0.3016184971098266], [0.1977868375072801, 0.060383167978104724]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.32, Test Accuracy: 85.52, Training Violation: 6.49, Test Violation: 8.84, Time cost: 3.375389337539673
[INFO][RUN] Surrogate Loss.
[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.39, Test Accuracy: 85.1, Training Violation: 7.07, Test Violation: 6.04, Time cost: 2.387014627456665
[INFO][RUN] Surrogate Loss.
Running fairness constraint: 0.05, Training Accuracy: 86.17, Test Accuracy: 85.66, Training Violation: 7.0, Test Violation: 5.59, Time cost: 2869.7358949184418
[INFO][RUN] Peer Loss with alpha = 0.1


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 378, in <module>
    pl_result = run_peerloss(tolerance, est=True, alpha=0.1)
  File "fair-classification-with-noisy-labels/run.py", line 275, in run_peerloss
    sweep = ExponentiatedGradient(PeerLoss(A_train, delta=delta, alpha=alpha),
  File "/home/avijit/projects/Awareness_vs_Unawareness/fair-classification-with-noisy-labels/PeerLoss.py", line 90, in __init__
    self.A[i] = 1./delta[A[i]]
TypeError: list indices must be integers or slices, not numpy.float64


('data/datasets/uci_adult/synthetic/female_groupsize0.5_version0/', 'Done')
['data/datasets/uci', 'adult/synthetic/gender', 'flip', 'labels0.4', 'version0/']
[[0.93679144 0.15355629]
 [0.06320856 0.84644371]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.43810589 0.40399365]
 [0.56189411 0.59600635]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.79924909 0.06275889]
 [0.20075091 0.93724111]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.5618941088739746, 0.40399365247289076], [0.20075090930423556, 0.06275889462634054]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.29, Test Accuracy: 85.54, Training Violation: 5.34, Test Violation: 11.71, Time cost: 14.068267583847046
[INFO][RUN] Surrogate Loss.
Running fairness constraint: 0.05, Training Accuracy: 89.17, Test Accuracy: 88.55, Training Violation: 7.52, Test Violation: 8.3, Time cost: 4326.68003988266
[INFO][RUN] Peer Loss with alpha = 0.1


Traceback (most recent call last):
  File "fair-classification-with-noisy-labels/run.py", line 378, in <module>
    pl_result = run_peerloss(tolerance, est=True, alpha=0.1)
  File "fair-classification-with-noisy-labels/run.py", line 275, in run_peerloss
    sweep = ExponentiatedGradient(PeerLoss(A_train, delta=delta, alpha=alpha),
  File "/home/avijit/projects/Awareness_vs_Unawareness/fair-classification-with-noisy-labels/PeerLoss.py", line 90, in __init__
    self.A[i] = 1./delta[A[i]]
TypeError: list indices must be integers or slices, not numpy.float64


('data/datasets/uci_adult/synthetic/female_groupsize0.7_version0/', 'Done')
['data/datasets/uci', 'adult/synthetic/gender', 'flip', 'labels0.5', 'version0/']
[[0.92513369 0.19716035]
 [0.07486631 0.80283965]]
[DEBUG][EST] Estimating Group 0
[DEBUG] Estimated Noise Matrix [[0.508035   0.50581049]
 [0.491965   0.49418951]].
[DEBUG][EST] Estimating Group 1
[DEBUG] Estimated Noise Matrix [[0.80063254 0.0619797 ]
 [0.19936746 0.9380203 ]].
True error rate is [[0.0, 0.0], [0.0, 0.0]].
Estimated error rate is [[0.4919649960222753, 0.5058104886769964], [0.19936745929483424, 0.06197970122020757]].


RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd


[INFO][RUN] Clean
Running fairness constraint: 0.05, Training Accuracy: 85.26, Test Accuracy: 85.44, Training Violation: 7.02, Test Violation: 6.52, Time cost: 20.2745099067688
[INFO][RUN] Surrogate Loss.


#### FairAdapt (Preproc.)

In [ ]:
# XY_df = pd.concat([X_train, y_train], axis=1)
# adj_mat = pd.DataFrame(
#     np.zeros((len(train_df.columns), len(train_df.columns)), dtype=int),
#     index=train_df.columns.values,
#     columns=train_df.columns.values
# )

# # Construct the adjacency matrix of the causal graph
# adj_mat.at[
#     ["sex", "age", "native-country"],
#     ["marital-status", "education-num", "workclass", "hours-per-week",
#      "occupation", "annual-income"]
# ] = 1
# adj_mat.at[
#     "marital-status",
#     ["education-num", "workclass", "hours-per-week", "occupation",
#      "annual-income"]
# ] = 1
# adj_mat.at[
#     "education-num",
#     ["workclass", "hours-per-week", "occupation", "annual-income"]
# ] = 1
# adj_mat.at[
#     ["workclass", "hours-per-week", "occupation"],
#     "annual-income"
# ] = 1

# FA = FairAdapt(prot_attr='sex', adj_mat = adj_mat)


# Xf_train, yf_train, Xf_test = FA.fit_transform(X_train, y_train, X_test)
# # y_pred_advrew = clf.predict(X_test)
# # writejson(y_pred_advrew,'adv_rew_pred.json')


#### TAKING TOO LONG TO PROCESS #####

In [139]:
set(X_train.columns).intersection(set(X_test.columns))

{'age',
 'capital-gain',
 'capital-loss',
 'education-num',
 'fnlwgt',
 'hours-per-week'}

In [136]:
X_test.columns

Index(['workclass_?', 'workclass_Federal-gov', 'workclass_Local-gov',
       'workclass_Never-worked', 'workclass_Private', 'workclass_Self-emp-inc',
       'workclass_Self-emp-not-inc', 'workclass_State-gov',
       'workclass_Without-pay', 'education_10th',
       ...
       'native-country_Trinadad&Tobago', 'native-country_United-States',
       'native-country_Vietnam', 'native-country_Yugoslavia', 'age', 'fnlwgt',
       'education-num', 'capital-gain', 'capital-loss', 'hours-per-week'],
      dtype='object', length=107)

In [ ]:
print('still runnung')